language: java
deploy:
  provider: releases
  api_key:
    secure: mHu9dbMriFleACjz1poD5qxJoZ/T2k2G5CG4xQdiCx1nIUFlnJyk73KgD7Qa/mZ6NFET0ZQB6kZ5k3rug6WyFyDoxyyEa9D7TywKdW/sjVTJcV89H7JUbrqSa2FY2l1SWSiqvOv7SDjGj1I0lst0h5zv3QrNYlPLncYxcNUZjpLUcaKfIqe4cMcltGEMhNCEoSMdwR0AaVXnYrUqwktFHzbMbiTpbk4e315DXKok374jQs7atiTgyYCL0UVZDjFkqkoq9kW2B1UnnT/b91JImg+pVRku5dCnCGnPhjYZmvK5KYHZ++QAcJ4HBEimx9VQrKymTghj+6/FqjA2VcSenNjn1FNh744N88QG1v/pCegG/8Oouot8mTNGhjpNiXYTt/ODWT+KfcCyOu83CW/mLllQFdcuA6jIZa9maev4Cr/1M8yKLd8kP0CJYcMZgjYz+iTWxoi2prUTeBRbA/UfYvRM3Fpwbj2HQtkMyOtmH3WQAXSyQbSh991ZdJZ0DZfEXGvrGKLn17wc/lQONBxRIP4j99bmtUexQMhd9ViGyyBLgUzk9EiGjf5eMRiZD5/k46OMaAPVTKemrLn/zbGEnMaVbWMLG1xEsrbCSfJxhMEOq9GOZwIPdEH7MBr8z66mS7B+pdWTYI8y/Y9xwYo4oMl5rSw0NBhrPhvW9D7RSC4=
  file:
  - 'target/BasePlugin.jar'
  skip_cleanup: true
  on:
    tags: true
