language: java
deploy:
  provider: releases
  api_key:
    secure: IS9kvevn9zxxOVuMaaDuPko72q8AvQMsi7BH+2bPkpz2H32EbV23hyVsysaNe+B8QD+fgO40q2SXqtKhXNjarGyUSWpOXrGU3hE+gWrd7Zgv2Pp/y3XJ22Ocb8zA8fYg4sqb7j5j33CuyAD3g/WUYkNoMgtoOs3aotJTjxwN5/eqLYf82+DuBtDiRk8RsiXh1nibN6s/CYGsRAo7duozxqWgClrvgH3m+NbCdBwGqPy30M+o+mahL7YFLvZFl66rwVmKDauSjdoTaR7b/1op/Sh8Fg1oLx2ZSuZRdTy41kqLzVGeYAC6qVgJlEyDfQJ49F1g9Ll4huPWkC+c6aojnhVL0tRhKpGz30qqcJeN3QqV7C8wPVQUIQenDF2jic3H9Yzbt5GcKuHw0pS3hlKGNnqMBbBEnHXtGnLK0ZegCYalZm6PIhvapANx5KTZWIy5w457F8avoNxyHMzSHpMU/c97rui7khDs/Kxyjye42if6R74FWCDgnCQRtH5H7bqY/C1gf0t0oa0HW610BSZZRqkkWibtukzxg7gv7IG95u85DCa3uoDoFO+h668SYc4mYI7DkL6ZkSWrIvSU8TK6XaT/9aLICCHC/R/FfV232XY6Q374fEfEIbnn0ZywfdNdRVZFH/nrKteJhf59ftWXM/fY7VgFJXflkvzIqI0OmLo=
  file: target/BasePlugin.jar
  skip_cleanup: true
  on:
    tags: true
